### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './kgs/ent2outRel.pkl'

### ISSUE THREAD

**Issue by jxrjlxc02** [algoflow19/SMedBERT#1]
run_ner.py -> missing file

**Comment by algoflow19** [comment]
谢谢关注，这个资源涉及知识图谱，得到许可后就会放上来，目前还需要一点点时间就好。

**Comment by algoflow19** [comment]
你好，我新上传了所需的文件，不过因为不让全放出来，只用了原来5%的实体，感觉是得争取一下多用点会更好，你可以跑跑试试看了，有什么问题可以尽管说

**Comment by jxrjlxc02** [comment]
> 你好，我新上传了所需的文件，不过因为不让全放出来，只用了原来5%的实体，感觉是得争取一下多用点会更好，你可以跑跑试试看了，有什么问题可以尽管说，如果你觉得这个问题解决了就再close issue吧。

thank you for quick reply!
and when i running run_pretraining.py, i can't find "aug_dev.txt" 
Could you just share few lines of those file?

FileNotFoundError: [Errno 2] No such file or directory: '(......)/aug_dev.txt'

**Comment by algoflow19** [comment]
Sure, it seems that you want to train your own model? I think it would be wonderful if someone would like to train the model with their knowledge graph since I can't release all resources used in our paper. I will describe the pre-training process in the hub soon.

**Comment by algoflow19** [comment]
Hi! I'm sorry for letting your guys waiting for so long, while I must re-check if the resources are properly authorized.
